### ISSUE TITLE
Issue Finding Package

### ISSUE THREAD

**Issue by DeveloperPaul123** [forexample/package-example#2]
I gave your example a try and I like how it is structured as well as how clear and concise the CMake is, but I ran into a problem. I ran `install` and successfully "installed" the Foo project.

When I try to use `Foo::bar` and `Foo::baz` in another project, the `find_package` fails because the `check_components` function fails when it's searching for the required components. Any ideas how to fix this so that the components are successfully found? If that check isn't there everything works fine.

**Comment by simogasp** [comment]
Hi, can you paste your `find_package` code. For me this works
```cmake
find_package(Foo CONFIG REQUIRED)

add_executable(boo boo.cpp)
target_link_libraries(boo Foo::bar)
```
(ie you don't need `COMPONENTS` in `find_package`)

**Comment by DeveloperPaul123** [comment]
This is the test code I used:

````cmake
cmake_minimum_required(VERSION 3.0)

project(FooTest) 

find_package(Foo REQUIRED COMPONENTS bar baz)

set(project_sources main.cpp)

add_executable(${PROJECT_NAME} ${project_sources})

target_link_libraries(${PROJECT_NAME} Foo::bar Foo::baz)
````

You are correct that `COMPONENTS` is not required, but it is common practice in larger libraries to only use the targets you need (i.e. like with `Qt5`). That being said the above code does not work. Below is the error message:

````
CMake Error at CMakeLists.txt:5 (find_package):
  Found package configuration file:

    C:/Program Files/Project/lib/cmake/Foo/FooConfig.cmake

  but it set Foo_FOUND to FALSE so package "Foo" is considered to be NOT
  FOUND.
````

**Comment by ruslo** [comment]
> You are correct that COMPONENTS is not required, but it is common practice in larger libraries to only use the targets you need (i.e. like with Qt5

Qt use it's own build system, not CMake. It does install `*Config.cmake` files for easy CMake integration though.

As for the `Foo` example: libraries `Foo::bar` and `Foo::baz` already installed at the moment of `find_package(Foo CONFIG REQUIRED)` call so you will not optimize anything by specifying components. If you want to install only `bar` but not `baz` in CMake you have to add such option to `Foo` project (like `FOO_BUILD_ONLY_BAR=ON`), but even in this case the call still will be `find_package(Foo CONFIG REQUIRED)` (i.e. without components).

**Comment by DeveloperPaul123** [comment]
> Qt use it's own build system, not CMake. It does install *Config.cmake files for easy CMake integration though.

Yes that's true. I just wanted to get the components check working with this example. 

It's not necessarily about optimization or what targets are actually installed, but more so being explicit in what components of a target library are needed in a given project. It's not really a big deal, just thought I'd see if there was a way to fix it.

**Comment by ruslo** [comment]
Generated file `*Config.cmake`, specifier `COMPONENTS` and `Foo::*` targets in general completely independent entities. What is the original problem you're trying to solve? You just want to have `COMPONENTS` in your `find_package` call? Take a look at `<package>_FIND_COMPONENTS` variable:
* `<package>_FIND_COMPONENTS`

As an example, Boost from Hunter (like Qt, Boost build not using CMake under the hood):
* https://github.com/ruslo/hunter/blob/27c96b7f27e4d3fd7cb05766a1517e029ce7a202/cmake/templates/BoostConfig.cmake.in#L69-L70

**Comment by DeveloperPaul123** [comment]
Yes that was the original goal, but if I'm being honest I didn't realize that they were separate entities. 

Thanks for the pointers, I'll take a look.

**Comment by simogasp** [comment]
> If you want to install only bar but not baz in CMake you have to add such option to Foo project (like FOO_BUILD_ONLY_BAR=ON), but even in this case the call still will be find_package(Foo CONFIG REQUIRED) (i.e. without components).

And in your `*Config.cmake.in` you can, for each target, define a proper `Foo_<comp>_FOUND` to true and false (where `<comp>` is `bar`, `baz` etc) according to eg `FOO_BUILD_ONLY_BAR`. That way if you specify `COMPONENTS` it should not fail. But I don't know if it is really the proper thing to do and the correct way to handle it. I never found any doc about that. Also, afaik, there is no way to get a variable containing the list of imported targets for a given package.

**Comment by ruslo** [comment]
> And in your *Config.cmake.in you can, for each target, define a proper Foo_<comp>_FOUND to true and false (where <comp> is bar, baz etc) according to eg FOO_BUILD_ONLY_BAR. That way if you specify COMPONENTS it should not fail.

I don't understand what is the benefits of such approach?

Also as alternative you can do:
```cmake
find_package(Foo CONFIG REQUIRED)
if(TARGET Foo::boo)
  # Handle optional Foo::boo
  target_link_libraries(... PUBLIC Foo::boo)
  target_compile_definitions(... PUBLIC ..._WITH_FOO_BOO=1)
endif()
```

**Comment by DeveloperPaul123** [comment]
@ruslo I think you're right with the above example. This approach only makes sense for something like `Qt5` where specifying targets actually changes what is imported. In other cases you can just check if a target exists before linking to it.

**Comment by simogasp** [comment]
> I don't understand what is the benefits of such approach?

well, me neither.. :-) It was a way (as I said, maybe the wrong way) to mimic the find_package with components boost-like. In your last example, if `Foo` can be built/provided without `Boo` you have to deal with the fact that Boo is optional in your CMakeFile as you did, while having a `find_package(Foo CONFIG REQUIRED COMPONENTS Boo)` will generate an error immediately (ie it is managed by the `*Config.cmake`). That's the only benefit I see (ie less code to write for lazy people like me). But, again, I'm in the continuous process of learning CMake myself (BTW thanks for this repository!), so I'm just discussing it rather than proposing solutions.

**Comment by DeveloperPaul123** [comment]
@simogasp Same here, still constantly learning about cmake all the time, especially with regard to creating libraries.
