### ISSUE TITLE
Use `LIB_INSTALL_DIR`

### ISSUE THREAD

**Issue by isaachier** [forexample/package-example#3]
@mrostecki added this [pull request](https://github.com/jaegertracing/jaeger-client-cpp/pull/102) to my project. I asked him to please post it here but I don't think he has had time to do so. I was wondering how you feel about this issue. Below is a quote from the linked PR.

> The common practice in cmake to allow to specify the libdir is using the LIB_INSTALL_DIR variable. The main use case of that variable is setting /usr/lib64 as the destination dir for libraries which is a common pattern in many Linux distributions.

**Comment by mrostecki** [comment]
It seems that it's already done, there is a commit made 2 months ago:

https://github.com/forexample/package-example/commit/d76608b4bbce97a0afedc127b1c3cefda6100bc1

The name of the variable is `CMAKE_INSTALL_LIBDIR`.

**Comment by isaachier** [comment]
Good catch my mistake.
