### ISSUE TITLE
Automating install of third parties packages

### ISSUE THREAD

**Issue by sancelot** [forexample/package-example#4]
I would like to setup third parties project like proposed in this example.

However, I would like that the setup of these third parties package are done by my main project cmake.

If the third party package is not there, then install it .... (most of them are git repository based)

have you got an idea on how to proceed ?

**Comment by ruslo** [comment]
I'm not sure I undestand the question, but I think it's out of scope of this example, there is no third party involved here. As for the automation of third party install you can check [Hunter](https://docs.hunter.sh/en/latest/). If you think about some general scenario probably question/discussion fits better the [CGold tutorials](https://github.com/ruslo/CGold) (e.g. as part of [this WIP section](https://cgold.readthedocs.io/en/latest/tutorials/install/samples.html)).

**Comment by solosuper** [comment]
@sancelot You could take a look at https://github.com/Crascit/DownloadProject for downloading an external project's source at CMake's configure step.

**Comment by ruslo** [comment]
Discussion is out of scope of this example, closing.
