### ISSUE TITLE
Monolithic build works only if commands add_subdirectory are in the right order

### ISSUE THREAD

**Issue by lguez** [forexample/package-example#7]
Thank you for this example. There is something that does not seem satisfying: the monolithic build works only if the order of commands `add_subdirectory` in the top-level `CMakeLists.txt` is correct. Is there not a way to improve on this? (Imagine a set of a dozen libraries with various dependencies between them.)

**Comment by ruslo** [comment]
> Is there not a way to improve on this?

In the case of the monolithic build, I don't see a sane way to make it better. You can try to do something like this:
```cmake
if(NOT TARGET foo::foo)
  add_subdirectory(${THIRD_PARTY_TOP_DIR}/third_party/foo)
endif()
```
But it looks pretty hairy.

> Imagine a set of a dozen libraries with various dependencies between them

It doesn't sound like a large set. Probably manually creating a dependency graph will be much easier and will lead to a clean solution.

**Comment by lguez** [comment]
> You can try to do something like this:

I do not really understand your suggestion. How would you do it in your own example (supposing you switch the order of the two `add_subdirectory` lines in your top-level `CMakeLists.txt`)?

**Comment by ruslo** [comment]
> I do not really understand your suggestion

If you don't have a target declared in the current scope (`if(NOT TARGET foo::foo)`) you import the target into the current scope by loading code from subdirectory (`add_subdirectory(.../foo)`).

> How would you do it in your own example (supposing you switch the order of the two add_subdirectory lines in your top-level CMakeLists.txt)?

See: https://github.com/forexample/package-example/commit/f12f974c7f81a4f252e14265881aed7272de9d09

Both
```cmake
if(NOT TARGET bar)
  add_subdirectory(Foo)
endif()

if(NOT TARGET boo)
  add_subdirectory(Boo)
endif()
```
and

```cmake
if(NOT TARGET boo)
  add_subdirectory(Boo)
endif()

if(NOT TARGET bar)
  add_subdirectory(Foo)
endif()
```
should work.

**Comment by lguez** [comment]
OK, thank you, I understand now. It does look hairy, indeed. Searching on the web, I have found another possibility: testing on `PARENT_DIRECTORY` property instead of testing on `TARGET`. See #8 . It looks better because we do not have to change anything to the top-level `CMakeLists.txt`. (But I do not know how to make it work with the `Foo::bar` alias.) What do you think of this solution?

**Comment by ruslo** [comment]
> I have found another possibility: testing on PARENT_DIRECTORY property instead of testing on TARGET

This pattern will work only in this particular case. Who said that parent directory will always provide the target? `Boo` can be used as a subdirectory of a random project and if there is no `Foo::bar` target in parent we should simply call `find_package(Foo CONFIG REQUIRED)`.

**Comment by lguez** [comment]
OK. Thank you.
